
service: serverless-lambda


provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1



functions:
  hello:
    handler: src/handler.agikFirstlambda
    timeout: 60 #seconds
    memorySize: 128 # mb
